# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/heorhii/bufferfs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/heorhii/bufferfs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/heorhii/bufferfs/CMakeFiles /home/heorhii/bufferfs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/heorhii/bufferfs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bfs_lib

# Build rule for target.
bfs_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bfs_lib
.PHONY : bfs_lib

# fast build rule for target.
bfs_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfs_lib.dir/build.make CMakeFiles/bfs_lib.dir/build
.PHONY : bfs_lib/fast

#=============================================================================
# Target rules for targets named bufferfs

# Build rule for target.
bufferfs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bufferfs
.PHONY : bufferfs

# fast build rule for target.
bufferfs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bufferfs.dir/build.make CMakeFiles/bufferfs.dir/build
.PHONY : bufferfs/fast

bufferfs.o: bufferfs.cpp.o
.PHONY : bufferfs.o

# target to build an object file
bufferfs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bufferfs.dir/build.make CMakeFiles/bufferfs.dir/bufferfs.cpp.o
.PHONY : bufferfs.cpp.o

bufferfs.i: bufferfs.cpp.i
.PHONY : bufferfs.i

# target to preprocess a source file
bufferfs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bufferfs.dir/build.make CMakeFiles/bufferfs.dir/bufferfs.cpp.i
.PHONY : bufferfs.cpp.i

bufferfs.s: bufferfs.cpp.s
.PHONY : bufferfs.s

# target to generate assembly for a file
bufferfs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bufferfs.dir/build.make CMakeFiles/bufferfs.dir/bufferfs.cpp.s
.PHONY : bufferfs.cpp.s

src/bfs_buffer.o: src/bfs_buffer.cpp.o
.PHONY : src/bfs_buffer.o

# target to build an object file
src/bfs_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfs_lib.dir/build.make CMakeFiles/bfs_lib.dir/src/bfs_buffer.cpp.o
.PHONY : src/bfs_buffer.cpp.o

src/bfs_buffer.i: src/bfs_buffer.cpp.i
.PHONY : src/bfs_buffer.i

# target to preprocess a source file
src/bfs_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfs_lib.dir/build.make CMakeFiles/bfs_lib.dir/src/bfs_buffer.cpp.i
.PHONY : src/bfs_buffer.cpp.i

src/bfs_buffer.s: src/bfs_buffer.cpp.s
.PHONY : src/bfs_buffer.s

# target to generate assembly for a file
src/bfs_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfs_lib.dir/build.make CMakeFiles/bfs_lib.dir/src/bfs_buffer.cpp.s
.PHONY : src/bfs_buffer.cpp.s

src/bfs_file.o: src/bfs_file.cpp.o
.PHONY : src/bfs_file.o

# target to build an object file
src/bfs_file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfs_lib.dir/build.make CMakeFiles/bfs_lib.dir/src/bfs_file.cpp.o
.PHONY : src/bfs_file.cpp.o

src/bfs_file.i: src/bfs_file.cpp.i
.PHONY : src/bfs_file.i

# target to preprocess a source file
src/bfs_file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfs_lib.dir/build.make CMakeFiles/bfs_lib.dir/src/bfs_file.cpp.i
.PHONY : src/bfs_file.cpp.i

src/bfs_file.s: src/bfs_file.cpp.s
.PHONY : src/bfs_file.s

# target to generate assembly for a file
src/bfs_file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfs_lib.dir/build.make CMakeFiles/bfs_lib.dir/src/bfs_file.cpp.s
.PHONY : src/bfs_file.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bfs_lib"
	@echo "... bufferfs"
	@echo "... bufferfs.o"
	@echo "... bufferfs.i"
	@echo "... bufferfs.s"
	@echo "... src/bfs_buffer.o"
	@echo "... src/bfs_buffer.i"
	@echo "... src/bfs_buffer.s"
	@echo "... src/bfs_file.o"
	@echo "... src/bfs_file.i"
	@echo "... src/bfs_file.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

